### ISSUE TITLE
Color scheme for tmux

### ISSUE THREAD

**Issue by MindTooth** [roosta/contrib-srcery#4]
Hi,

Been at it again..  Couldn't have a tmux that didn't conform.  Borrowed some ideas from [Arctic Ice Studios](https://github.com/arcticicestudio/nord-tmux) & [jimeh](https://github.com/jimeh/tmux-themepack).  Maybe at some point I'll extend it more to be a complete style — with options, etc., and at a later time we could create a new repo, so installing it via package manager would be possible.

Thoughts?

<img width="1591" alt="screen shot 2018-05-15 at 14 29 03" src="https://user-images.githubusercontent.com/33870508/40056688-66f3cbf0-584c-11e8-9cf1-b183f11fa642.png">
<img width="1591" alt="screen shot 2018-05-15 at 14 33 19" src="https://user-images.githubusercontent.com/33870508/40056916-0d513456-584d-11e8-8788-d86500922f8c.png">
<img width="1591" alt="screen shot 2018-05-15 at 14 33 40" src="https://user-images.githubusercontent.com/33870508/40056917-0d6efbb2-584d-11e8-801b-d0bd7a40f413.png">
<img width="1591" alt="screen shot 2018-05-15 at 14 34 02" src="https://user-images.githubusercontent.com/33870508/40056918-0d8ef598-584d-11e8-9c71-4178d5202bbf.png">

Initial code:
```tmux
# Mein Status Style
set -g status-style fg=brightwhite,bg=brightblack

# Left Side Style
set -g status-left-style fg=brightwhite,bg=colour237
set -g status-left-length 40
set -g status-left "#[fg=brightwhite,bg=colour237,bold] #S #[fg=brightwhite,bg=colour236,nobold] #(whoami) #[fg=brightwhite,bg=brightblack] #I:#P #(page_mode) "

# Right side of status bar
set -g status-right-style fg=brightwhite,bg=colour237
set -g status-right-length 150
set -g status-right "#[fg=brightwhite,bg=brightblack] %H:%M #[fg=brightwhite,bg=colour236] %d-%b-%y #[fg=brightwhite,bg=colour237,bold] #H "

# Window status
set -g window-status-format "#[fg=default,bg=default,italics] #I:#W (#F) "
set -g window-status-current-format "#[fg=brightwhite,bg=colour236,bold] #I:#W (#F) "

# Current window status
set -g window-status-current-style fg=colour235,bg=colour100

# Pane border
set -g pane-border-style fg=colour236,bg=default
set -g pane-active-border-style fg=colour238,bg=default

# Clock mode
set -g clock-mode-colour brightwhite
set -g clock-mode-style 24

# Command message
set -g message-command-style fg=brightwhite,bg=brightblack

set -g mode-style fg=brightwhite,bold,bg=colour237

# Message
set -g message-style fg=brightwhite,bg=brightblack

# Pane number indicator
set -g display-panes-colour colour239
set -g display-panes-active-colour brightwhite

set -g window-status-separator ""
```

**Comment by roosta** [comment]
Looks great. I got a tmux theme as well, but much more bare bones than yours. I'll have a proper look at this once I'm done at work.

**Comment by roosta** [comment]
![tmux](https://user-images.githubusercontent.com/4509009/40067602-ce1e5f24-5866-11e8-80fc-fe6d57ed3626.png)
Heres mine, got the panes on the left side, and the session|host on the right.

**Comment by MindTooth** [comment]
Then I'll add it.  Not sure about the pane border quite yet.  Feel them being to soft.  But I can't completely mimic the Vim way, as the divider is different between horizontal and vertical.

**Comment by roosta** [comment]
I prefer my pane borders very visible, hence the magenta and bright white colors. Got the same thing going in [i3wm](https://i3wm.org/). I also made a tmux plugin that flashes the active pane when you switch. I just really dislike not knowing where I am at any given time.

**Comment by MindTooth** [comment]
Added support for [tmux-prefix-highlight](https://github.com/tmux-plugins/tmux-prefix-highlight).  Will attempt a powerline version soon.

### Prefix Mode
<img width="1027" alt="screen shot 2018-05-17 at 14 48 06" src="https://user-images.githubusercontent.com/33870508/40178275-56d74c38-59e1-11e8-9c55-2ed5f05385f3.png">


### Copy Mode
<img width="1027" alt="screen shot 2018-05-17 at 14 46 09" src="https://user-images.githubusercontent.com/33870508/40178196-12788304-59e1-11e8-91b3-327042bde7f6.png">

**Comment by roosta** [comment]
very nice, keep up the good work.

**Comment by MindTooth** [comment]
Powerline glyphs, but subtle.  They are not in with Vim yet?

<img width="996" alt="screen shot 2018-05-17 at 18 30 40" src="https://user-images.githubusercontent.com/33870508/40190999-8579397e-5a00-11e8-977b-0326d04c35b3.png">

**Comment by MindTooth** [comment]
So this happened..  I'll stop for now :P

https://github.com/MindTooth/tmux-srcery

**Comment by roosta** [comment]
:D powerline is quite in with vim, I'm just not personally fond of them, I think they're a lot of hassle to set up and doesn't add anything. Looks cool though.

**Comment by MindTooth** [comment]
Crazy idea, what is you thoughts on creating a org that we can have every individual scheme under — the ones that needs to at least in the beginning, like https://github.com/arcticicestudio?  That is only if it is something that you could stand by.  I follow your opinion.  As I have truly fallen in love as you can see ;)

The reason I ask, is I like a more central place, but also that e.g. using [TPM](https://github.com/tmux-plugins/tpm) to install tmux plugins/themes, the theme need to be at top level.  And the added benefit that it might be easier to concentrate in individual schemes.

P.S. On a later note, I would like some guidelines on how to best comment the code (formatting of the code block, and make that universal.)

**Comment by roosta** [comment]
I'm not adverse to creating an org, it makes sense like you suggested for stuff that needs to be top level. I'll have a look at that over the weekend. 
  
As for guidelines, haven't really thought to much about that, your best judgment is as good as mine I think. Most of what I can come up with is either just common sense, or completely subjective. If you were to press me I guess I got opinions but not much more. Besides whatever I say now, is surly not gonna be reflected in my code :D

I'm liking `srcery-colors` for name.

**Comment by roosta** [comment]
Think I'm gonna hold of creating an org for the time being. We can link your tmux theme in the contrib repo for now if you'd like, and we'll see about creating an org when there is a bit more content to put in it.

**Comment by MindTooth** [comment]
Sure.  Fine with me 👍 

I'll review the code more this week, and add a link to it.

**Comment by roosta** [comment]
So, I finally got around to creating an org. Added you as a member so feel free to add your tmux theme and whatever else you feel fits.

**Comment by roosta** [comment]
Also I was thinking another name for this repo, any suggestions?

**Comment by roosta** [comment]
alright, renamed the repos, and I agree that we should split out to srcery-terminal and srcery-shell and whatever else we got. I thought I sent you an invite when I created the org but seems not. I've re-sent it now.

**Comment by MindTooth** [comment]
Thanks.  First org ever for me 😆

**Comment by roosta** [comment]
It was a good suggestion. Welcome to srcery-colors :D

**Comment by MindTooth** [comment]
http://mindtooth.no/srcery.github.io  Coming along 😆  Also, felt a bit unsure where to discuss stuff like this.  New thread in extra maybe?

Care to rename the tmux one, and give me some permissions?  Moved before I had named it correctly.

**Comment by roosta** [comment]
Maybe add an discussion thread over at https://github.com/srcery-colors/srcery ? I've set default permission to `write`, sorry about that, I'm new to this whole organization thing myself. Set you as admin on tmux-srcery. Can you change the name now?

**Comment by roosta** [comment]
Also the site looks awesome!

**Comment by roosta** [comment]
Or a thread in extras seems as good an idea

**Comment by MindTooth** [comment]
> Also the site looks awesome!

Thanks, btw. 😊
