### ISSUE TITLE
Srcery for Steam [WIP]

### ISSUE THREAD

**Issue by MindTooth** [roosta/contrib-srcery#6]
Hi,

Just wanted to share some minor progress on a theme for Steam.  Like I have nothing else to do 💃 😄 

<img width="1582" alt="screen shot 2018-06-04 at 12 23 21" src="https://user-images.githubusercontent.com/33870508/40912545-2ab6d5aa-67f2-11e8-869d-4300310fb557.png">

Let me just be the first to say, that this is a big undertaking.  It's a large surface to tough, with thousands of options.

Also, just asked Steam/Valve if I could share that work on e.g. GitHub 👍 

Ed1t:  Given a ambiguous answer.

###  Resources:
* https://developer.valvesoftware.com/wiki/Main_Page
* https://support.steampowered.com/kb_article.php?ref=1987-WYGJ-3701

**Comment by roosta** [comment]
Looks great as always, push away when ready :) Also, Factorio is an awesome game.

**Comment by MindTooth** [comment]
> We do not offer technical support for development tools or user made content. Unfortunately, we can't provide advice or guidance on how you should use custom skin browser or changers, but overall these are not supported and may result in you being disconnected by VAC.
> 
> Please see our article with [Resources for APIs, Source SDK, Mapping, and Dedicated Servers](http://support.steampowered.com/kb_article.php?ref=1987-WYGJ-3701) for information that may be of help.
> 
> Additional resources may be found on the [Valve Developer Wiki](http://developer.valvesoftware.com/) and in our [discussions](http://steamcommunity.com/discussions/).
> 
> If there's something else we can help with please let me know - I'll be happy to help how I can. 
> 
> Regards,	
> Sterling

Guess I need a bit more detective work 😕

**Comment by roosta** [comment]
Always fun ricing proprietary software. I've used some steam skins in the past and seems they often break for no good reason, and valve isn't being very helpful as you've pointed out. Good luck :)
